services:
  reverse_proxy:
    container_name: reverse_proxy
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: ./logs
        target: /var/log/nginx
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
